[package]
name = "vnc-rs"
version = "0.0.1"
edition = "2021"
author = "Jovi Hsu <jv.hsu@outlook.com>"
license = "BSD 3-Clause"
readme = "README.md"
repository = "https://github.com/HsuJv/vnc-rs"
homepage = "https://github.com/HsuJv/vnc-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#error
thiserror = "^1.0"
anyhow = "^1.0"

#log
tracing = { version = "^0.1", features = ["log"] }

# async
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "^1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "^1", features = [ 
    "sync",
    "macros",
    "io-util",
    "rt",
    "time"
    ]}

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
